variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zone" {}
variable "wavelength_zone" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "instance_type" {}
variable "keypair" {}
variable "encrypt_volumes" {}
variable "cidr_for_access" {}
variable "fortios_version" {}
variable "license_type" {}
variable "fgt_byol_license" {}
variable "fgt_fortiflex_token" {}
variable "tag_name_prefix" {}
variable "fgt_public_ip" {}
variable "fgt_private_ip" {}
variable "ca_cert" {}
variable "fgt_key" {}
variable "fgt_cert" {}
variable "fgt_gui_port" {}
variable "sslvpn_username" {}
variable "sslvpn_tunnel_ip" {}
variable "sslvpn_port" {}
variable "carrier_ip" {}
